name: Snyk Security Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}


    - name: Install Snyk CLI
      run: npm install -g snyk

    - name: Snyk Auth
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      run: snyk auth "$SNYK_TOKEN"

    - name: Run Snyk Code Test
      run: snyk code test 
